docs: add oss standard files/resources
checkly/checkly-operator pull request #15
Opened 2022-07-06 00:14 UTC by ianaya89

Add Checkly open-source best practices:

- SECURITY
- LICENSE
- CoC
- Issue templates
- Helper GH actions
- Remove sonar stuff (until we enable it)
- Readme tweaks

@akosveres let me know your thoughts on this. This is the format we use to have in our OSS projects but of course, we are open to ideas, feedback, or whatever is considered worth changing.

2022-07-06 12:14 UTC, ianaya89 commented
@akosveres if you think is ok, I can remove that

2022-07-06 16:47 UTC, akosveres approved these changes
LGTM

2022-07-06 17:45 UTC, ianaya89 commented
@akosveres that is a fair point, I need to double-check. Can you point me to the SDK repo?

2022-07-20 08:21 UTC, akosveres commented
Okay, sounds good to me.

2022-09-08 13:55 UTC, danielpaulus requested changes
Good stuff! just a nitpick and request for adding a small ci job rather than relying on contributors to run go fmt.

2022-09-08 13:55 UTC, danielpaulus commented on README.md
> +A kubernetes operator for [checklyhq.com](https://checklyhq.com). This operator can create Checkly checks and groups based of kubernetes CRDs and Ingress object annotations.
#nit: should be "based on"

2022-09-08 13:55 UTC, danielpaulus commented on .github/pull_request_template.md
> +* [ ] Go code is formatted with `go fmt`
we should just make this a part of some github action and go fmt as a pr check.

2022-09-12 13:15 UTC, danielpaulus commented on .github/pull_request_template.md
> +* [ ] Go code is formatted with `go fmt`
never mind, go test does that automatically. I wonder if this is then really needed it the template. But have no strong opinion about it.

2023-05-09 13:33 UTC, closed without merging