docs(general): Add general documentation
checkly/checkly-operator pull request #26
Opened 2022-08-15 13:28 UTC by akosveres

2022-09-08 13:56 UTC, danielpaulus commented
These are only documentation changes, I do like it when there is a short PR description though.

2022-09-08 14:25 UTC, danielpaulus requested changes
just a few typos, I haven't tried this process yet. Will do it later to double check it works

2022-09-08 14:25 UTC, danielpaulus commented on docs/README.md
> +Please look at the bellow examples and change the supplied data so it fits your needs the best. Save the example into individual files and apply them when ready:
bellow

2022-09-08 14:25 UTC, danielpaulus commented on docs/README.md
> +The `AlertChannel` resource is clustered scoped, it can be used in any check group but it also means that the name of the resource has to be unique in the kubernetes cluster.
cluster scoped?

2022-09-12 08:19 UTC, akosveres commented
> just a few typos, I haven't tried this process yet. Will do it later to double check it works

All updated and fixed conflicts.

2022-09-12 13:10 UTC, danielpaulus approved these changes

2022-09-12 13:10 UTC, merged